// Code generated by crane from Rocq sources. DO NOT EDIT.
package main

type listImpl struct {
	tag  int
	c1f0 any
	c1f1 any
}

type list[T1 any] = *listImpl

var nil_ *listImpl = &listImpl{tag: 0}

func cons(a0 any, a1 any) *listImpl {
	return &listImpl{tag: 1, c1f0: a0, c1f1: a1}
}

func length(l any) uint {
	return (func() uint {
		scrut1 := any(l).(*listImpl)
		switch scrut1.tag {
		case 0:
			return uint(0)
		case 1:
			l_ := scrut1.c1f1
			return uint((length((l_).(list[any])) + 1))
		}
		panic("unreachable")
	})()
}

func app(l any, m any) list[any] {
	return (func() list[any] {
		scrut2 := any(l).(*listImpl)
		switch scrut2.tag {
		case 0:
			return (m).(list[any])
		case 1:
			a := scrut2.c1f0
			l1 := scrut2.c1f1
			return cons(a, app((l1).(list[any]), (m).(list[any])))
		}
		panic("unreachable")
	})()
}
