// Code generated by crane from Rocq sources. DO NOT EDIT.
package main

type sdl_key int

const (
	KeyEscape sdl_key = iota
	KeyQ
	KeyUp
	KeyDown
	KeyLeft
	KeyRight
	KeyW
	KeyA
	KeyS
	KeyD
	KeySpace
)

type sdl_eventImpl struct {
	tag  int
	c1f0 any
}

type sdl_event = *sdl_eventImpl

var EventQuit *sdl_eventImpl = &sdl_eventImpl{tag: 0}

func EventKeyDown(a0 any) *sdl_eventImpl {
	return &sdl_eventImpl{tag: 1, c1f0: a0}
}
