// Code generated by crane from Rocq sources. DO NOT EDIT.
package main

func nth(n any, l any, default0 any) any {
	return func() any {
		var _sni_ any = n
		_su_ := _sni_.(uint)
		if _su_ == 0 {
			return (func() any {
				scrut1 := any(l).(*listImpl)
				switch scrut1.tag {
				case 0:
					return default0
				case 1:
					x := scrut1.c1f0
					return x
				}
				panic("unreachable")
			})()
		} else {
			m := _su_ - 1
			return (func() any {
				scrut2 := any(l).(*listImpl)
				switch scrut2.tag {
				case 0:
					return default0
				case 1:
					l_ := scrut2.c1f1
					return nth(m, (l_).(list[any]), default0)
				}
				panic("unreachable")
			})()
		}
	}()
}
