// Code generated by crane from Rocq sources. DO NOT EDIT.
package main

func nth(n any, l any, default0 any) any {
	return func() any {
		if (n).(uint) == 0 {
			return (func() any {
				lImpl := any(l).(*listImpl)
				switch lImpl.tag {
				case 0:
					return default0
				case 1:
					x := lImpl.c1f0
					return x
				}
				panic("unreachable")
			})()
		} else {
			m := (n).(uint) - 1
			return (func() any {
				lImpl2 := any(l).(*listImpl)
				switch lImpl2.tag {
				case 0:
					return default0
				case 1:
					l_ := lImpl2.c1f1
					return nth(m, (l_).(list[any]), default0)
				}
				panic("unreachable")
			})()
		}
	}()
}
