// Code generated by crane from Rocq sources. DO NOT EDIT.
package main

func pred(n uint) uint {
	return (func() any {
		if n == 0 {
			return n
		} else {
			u := n - 1
			return u
		}
	}()).(uint)
}

func add(n uint, m uint) uint {
	return (func() any {
		if n == 0 {
			return m
		} else {
			p := n - 1
			return uint((add(p, m) + 1))
		}
	}()).(uint)
}

func mul(n uint, m uint) uint {
	return (func() any {
		if n == 0 {
			return uint(0)
		} else {
			p := n - 1
			return add(m, mul(p, m))
		}
	}()).(uint)
}

func sub(n uint, m uint) uint {
	return (func() any {
		if n == 0 {
			return n
		} else {
			k := n - 1
			return (func() any {
				if m == 0 {
					return n
				} else {
					l := m - 1
					return sub(k, l)
				}
			}()).(uint)
		}
	}()).(uint)
}

func eqb(n uint, m uint) bool {
	return (func() any {
		if n == 0 {
			return (func() any {
				if m == 0 {
					return true
				} else {
					_ = m - 1
					return false
				}
			}()).(bool)
		} else {
			n_ := n - 1
			return (func() any {
				if m == 0 {
					return false
				} else {
					m_ := m - 1
					return eqb(n_, m_)
				}
			}()).(bool)
		}
	}()).(bool)
}

func leb(n uint, m uint) bool {
	return (func() any {
		if n == 0 {
			return true
		} else {
			n_ := n - 1
			return (func() any {
				if m == 0 {
					return false
				} else {
					m_ := m - 1
					return leb(n_, m_)
				}
			}()).(bool)
		}
	}()).(bool)
}

func ltb(n uint, m uint) bool {
	return leb(uint((n + 1)), m)
}
